server:
  port: 8085
  error:
    include-message: always

spring:
  application:
    name: transaction-service
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: balance-update-topic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: "event:com.thefuture.transactionservice.event.BalanceUpdateEvent"

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

