server:
  port: 8085
  error:
    include-message: always

spring:
  application:
    name: transaction-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

