kafka:
  topics:
    transaction-listener: transaction-listener
#

server:
  port: 8085
  error:
    include-message: always

spring:
  application:
    name: transaction-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


