kafka:
  topics:
    transaction-listener: transaction-listener

#

server:
  port: 8081
  error:
    include-message: always

spring:
  sql:
    init:
      mode: always
      continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5424/account-service
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  elasticsearch:
    uris: http://localhost:9200
  application:
    name: account-service
#  kafka:
#    topic: balance-update-topic
#    bootstrap-servers: localhost:9092
#    template:
#      default-topic: balance-update-topic
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      group-id: balance-update-topic

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
